{
  "comments": [
    {
      "key": {
        "uuid": "5ac4a560_7a9dff58",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 10,
      "author": {
        "id": 1000935
      },
      "writtenOn": "2015-12-10T22:50:23Z",
      "side": 1,
      "message": "rpm -q --whatprovides python-distribute\npython-setuptools-17.1.1-3.fc22.noarch\n\nThis compat provide is in python-* and not in python2-* so this seems to be yet another python2-* FAIL :(\nBut still unclear why exactly it doesn\u0027t work, needs to be investigated.",
      "revId": "2b6600b257ff6d39f4e9cc4722c1b02b83056656",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}